title: notokrs.dev
email: rusnoto030@gmail.com
description: >-
  belum ada.
baseurl: ""
url: ""
github_username: notokrs

# Build settings
include: ["_pages"]
sass:
  sass_dir: _sass
kramdown:
  syntax_highlighter: rouge
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: true
plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll-archives

# TOC Settings
toc:
 ordered_list: false
 min_level: 1
 max_level: 6
 list_class: toc
 list_class: toc__list
 sublist_class: toc__sublist

# Jekyll Archives
jekyll-archives:
 enabled: ["tags"]
 layout: archive
 permalinks:
    tag: '/tag/:name/'
