title: notokrs portofolio
email: rusnoto030@gmail.com
description: Rusnoto Portofolio Website
baseurl: ""
url: "https://notokrs.github.io"
github_username: notokrs

# Build settings
include: ["_pages"]
sass:
  sass_dir: _sass
  style: compressed
kramdown:
  syntax_highlighter: rouge
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: true
plugins:
  - rouge
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag

# Jekyll Archives
jekyll-archives:
  enabled: ["tags"]
  layout: archive
  permalinks:
    tag: "/tag/:name/"
