title: notokrs.dev
email: rusnoto030@gmail.com
description: >-
  belum ada.
baseurl: ""
url: "https://notokrs.github.io"
github_username: notokrs

# Build settings
include: ["_pages"]
sass:
  sass_dir: _sass
kramdown:
  syntax_highlighter: rouge
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: true
plugins:
  - jekyll-feed
  - jekyll-archives

# Jekyll Archives
jekyll-archives:
  enabled: ["tags"]
  layout: archive
  permalinks:
    tag: "/tag/:name/"
